### ISSUE TITLE
Maintainance?

### ISSUE THREAD

**Issue by LDprg** [yawnt/declarative-nix-flatpak#2]
Sorry if the question sounds a bit rude. However is this repo still maintained?

**Comment by yawnt** [comment]
Hey,
It was kinda working when last I tried, however I am not using it anymore as the application I wanted to use has issues with flatpak itself.
Have you encountered any issues?

**Comment by LDprg** [comment]
No, I just want to decide between this project and [this one](https://github.com/GermanBread/declarative-flatpak). So I can choose the one with better maintainance. 
Thx for responding
